// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6_CWbXU0sm9tiIzBCJIvKT39fxNMCnGk',
    appId: '1:569491466039:android:88951d0d399e66ec125cb2',
    messagingSenderId: '569491466039',
    projectId: 'parrot-number-game',
    storageBucket: 'parrot-number-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABzfE-TlTgezJ64nf7wW9EXa2_UWcvUPw',
    appId: '1:569491466039:ios:6e43417ba9f00e64125cb2',
    messagingSenderId: '569491466039',
    projectId: 'parrot-number-game',
    storageBucket: 'parrot-number-game.appspot.com',
    androidClientId: '569491466039-pc32i9b4t2ku3idpf5gohmi2dckkfms1.apps.googleusercontent.com',
    iosClientId: '569491466039-3ovdq2ga5h3s81qut1h4qrvaltuomu1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.parrotNumber',
  );
}
